export const SET_ERROR = 'SET_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';

export const FORM_SET_CSRF_TOKEN = 'FORM_SET_CSRF_TOKEN';

export const UI_SET_GRANT_VIEW = 'UI_SET_GRANT_VIEW';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_SET_ID_TOKEN = 'AUTH_SET_ID_TOKEN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
