export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const SIGN_OUT = 'SIGN_OUT';

export const SET_ERROR = 'SET_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';

export const FORM_SET_CSRF_TOKEN = 'FORM_SET_CSRF_TOKEN';

export const GRANTS_SET_VERB = 'GRANTS_SET_VERB';
export const GRANTS_SET_IDS = 'GRANTS_SET_IDS';

export const APOLLO_QUERY_RESULT = 'APOLLO_QUERY_RESULT';
